// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: applications.sql

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

const getApplication = `-- name: GetApplication :one
SELECT id, name FROM applications
WHERE
    id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i Application
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getApplicationByName = `-- name: GetApplicationByName :one
SELECT id, name FROM applications
WHERE
    name = $1
`

func (q *Queries) GetApplicationByName(ctx context.Context, name string) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByName, name)
	var i Application
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertApplication = `-- name: InsertApplication :exec
INSERT INTO applications
    ( "name" ) VALUES
    ( $1)
`

func (q *Queries) InsertApplication(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, insertApplication, name)
	return err
}
