// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package postgresql

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID     uuid.UUID
	Name   string
	Secret uuid.UUID
	Keys   []string
}

type Group struct {
	ID            uuid.UUID
	Name          string
	ApplicationID uuid.UUID
	Permissions   []byte
}

type User struct {
	Email    string
	Name     string
	Password string
	Status   pgtype.Text
	Groups   []byte
}
