// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/discord-gophers/goapi-gen version v0.3.0 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/discord-gophers/goapi-gen/runtime"
	openapi_types "github.com/discord-gophers/goapi-gen/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/render"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for Status.
var (
	UnknownStatus = Status{}

	StatusActive = Status{"active"}

	StatusInactive = Status{"inactive"}
)

// Application defines model for Application.
type Application struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// BasicCreationResponse defines model for BasicCreationResponse.
type BasicCreationResponse struct {
	Feedback string `json:"feedback"`
	ID       string `json:"id"`
}

// BasicResponse defines model for BasicResponse.
type BasicResponse struct {
	Feedback string `json:"feedback"`
}

// Error defines model for Error.
type Error struct {
	Feedback string `json:"feedback"`
}

// Group defines model for Group.
type Group struct {
	ID   string `json:"id"`
	Name string `json:"name"`

	// Este objeto é composto pela definição de permissões onde a chave é o identificador do recurso e o valor é o número da permissão
	Permissions map[string]interface{} `json:"permissions"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError struct {
	Feedback string `json:"feedback"`
}

// LoginCredentials defines model for LoginCredentials.
type LoginCredentials struct {
	Application string              `json:"application" validate:"required"`
	Email       openapi_types.Email `json:"email" validate:"required"`
	Password    string              `json:"password" validate:"required,min=8,max=32"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Feedback string `json:"feedback"`
	Token    string `json:"token"`
}

// NewApplication defines model for NewApplication.
type NewApplication struct {
	Name string `json:"name" validate:"required"`
}

// NewGroup defines model for NewGroup.
type NewGroup struct {
	Name string `json:"name" validate:"required,min=3"`
}

// NewUser defines model for NewUser.
type NewUser struct {
	Email    openapi_types.Email `json:"email" validate:"required,email"`
	GroupID  string              `json:"groupId" validate:"required"`
	Name     string              `json:"name" validate:"required,min=3"`
	Password string              `json:"password" validate:"required,min=8,max=32"`
}

// Permission defines model for Permission.
type Permission struct {
	Key        string `json:"key" validate:"required,min=3"`
	Permission int    `json:"permission" validate:"required"`
}

// Unauthorized defines model for Unauthorized.
type Unauthorized struct {
	Feedback string `json:"feedback"`
}

// User defines model for User.
type User struct {
	Email openapi_types.Email `json:"email"`
	Group struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	} `json:"group"`
	Name   string `json:"name"`
	Status Status `json:"status"`
}

// UserUpdated defines model for UserUpdated.
type UserUpdated struct {
	GroupID     string               `json:"groupId" validate:"required"`
	Name        string               `json:"name" validate:"required,min=3"`
	NewEmail    *openapi_types.Email `json:"newEmail,omitempty" validate:"email"`
	NewPassword *string              `json:"newPassword,omitempty" validate:"min=8,max=32"`
	Status      Status               `json:"status"`
}

// N400 defines model for 400.
type N400 Error

// N401 defines model for 401.
type N401 Unauthorized

// N500 defines model for 500.
type N500 InternalServerError

// Status defines model for Status.
type Status struct {
	value string
}

func (t *Status) ToValue() string {
	return t.value
}
func (t Status) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.value)
}
func (t *Status) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	return t.FromValue(value)
}
func (t *Status) FromValue(value string) error {
	switch value {

	case StatusActive.value:
		t.value = value
		return nil

	case StatusInactive.value:
		t.value = value
		return nil

	}
	return fmt.Errorf("unknown enum value: %v", value)
}

// NewApplicationJSONBody defines parameters for NewApplication.
type NewApplicationJSONBody NewApplication

// AddPermissionJSONBody defines parameters for AddPermission.
type AddPermissionJSONBody Permission

// UpdatePermissionJSONBody defines parameters for UpdatePermission.
type UpdatePermissionJSONBody Permission

// NewGroupJSONBody defines parameters for NewGroup.
type NewGroupJSONBody NewGroup

// NewUserJSONBody defines parameters for NewUser.
type NewUserJSONBody NewUser

// UserUpdateJSONBody defines parameters for UserUpdate.
type UserUpdateJSONBody UserUpdated

// LoginJSONBody defines parameters for Login.
type LoginJSONBody LoginCredentials

// NewApplicationJSONRequestBody defines body for NewApplication for application/json ContentType.
type NewApplicationJSONRequestBody NewApplicationJSONBody

// Bind implements render.Binder.
func (NewApplicationJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// AddPermissionJSONRequestBody defines body for AddPermission for application/json ContentType.
type AddPermissionJSONRequestBody AddPermissionJSONBody

// Bind implements render.Binder.
func (AddPermissionJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// UpdatePermissionJSONRequestBody defines body for UpdatePermission for application/json ContentType.
type UpdatePermissionJSONRequestBody UpdatePermissionJSONBody

// Bind implements render.Binder.
func (UpdatePermissionJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// NewGroupJSONRequestBody defines body for NewGroup for application/json ContentType.
type NewGroupJSONRequestBody NewGroupJSONBody

// Bind implements render.Binder.
func (NewGroupJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// NewUserJSONRequestBody defines body for NewUser for application/json ContentType.
type NewUserJSONRequestBody NewUserJSONBody

// Bind implements render.Binder.
func (NewUserJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// UserUpdateJSONRequestBody defines body for UserUpdate for application/json ContentType.
type UserUpdateJSONRequestBody UserUpdateJSONBody

// Bind implements render.Binder.
func (UserUpdateJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// Bind implements render.Binder.
func (LoginJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// Response is a common response struct for all the API calls.
// A Response object may be instantiated via functions for specific operation responses.
// It may also be instantiated directly, for the purpose of responding with a single status code.
type Response struct {
	body        interface{}
	Code        int
	contentType string
}

// Render implements the render.Renderer interface. It sets the Content-Type header
// and status code based on the response definition.
func (resp *Response) Render(w http.ResponseWriter, r *http.Request) error {
	w.Header().Set("Content-Type", resp.contentType)
	render.Status(r, resp.Code)
	return nil
}

// Status is a builder method to override the default status code for a response.
func (resp *Response) Status(code int) *Response {
	resp.Code = code
	return resp
}

// ContentType is a builder method to override the default content type for a response.
func (resp *Response) ContentType(contentType string) *Response {
	resp.contentType = contentType
	return resp
}

// MarshalJSON implements the json.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(resp.body)
}

// MarshalXML implements the xml.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.Encode(resp.body)
}

// ApplicationsListJSON200Response is a constructor method for a ApplicationsList response.
// A *Response is returned with the configured status code and content type from the spec.
func ApplicationsListJSON200Response(body []Application) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// ApplicationsListJSON401Response is a constructor method for a ApplicationsList response.
// A *Response is returned with the configured status code and content type from the spec.
func ApplicationsListJSON401Response(body Unauthorized) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// ApplicationsListJSON500Response is a constructor method for a ApplicationsList response.
// A *Response is returned with the configured status code and content type from the spec.
func ApplicationsListJSON500Response(body InternalServerError) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// NewApplicationJSON201Response is a constructor method for a NewApplication response.
// A *Response is returned with the configured status code and content type from the spec.
func NewApplicationJSON201Response(body BasicCreationResponse) *Response {
	return &Response{
		body:        body,
		Code:        201,
		contentType: "application/json",
	}
}

// NewApplicationJSON400Response is a constructor method for a NewApplication response.
// A *Response is returned with the configured status code and content type from the spec.
func NewApplicationJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// NewApplicationJSON401Response is a constructor method for a NewApplication response.
// A *Response is returned with the configured status code and content type from the spec.
func NewApplicationJSON401Response(body Unauthorized) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// NewApplicationJSON500Response is a constructor method for a NewApplication response.
// A *Response is returned with the configured status code and content type from the spec.
func NewApplicationJSON500Response(body InternalServerError) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// DeleteGroupJSON200Response is a constructor method for a DeleteGroup response.
// A *Response is returned with the configured status code and content type from the spec.
func DeleteGroupJSON200Response(body BasicResponse) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// DeleteGroupJSON400Response is a constructor method for a DeleteGroup response.
// A *Response is returned with the configured status code and content type from the spec.
func DeleteGroupJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// DeleteGroupJSON401Response is a constructor method for a DeleteGroup response.
// A *Response is returned with the configured status code and content type from the spec.
func DeleteGroupJSON401Response(body Unauthorized) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// DeleteGroupJSON500Response is a constructor method for a DeleteGroup response.
// A *Response is returned with the configured status code and content type from the spec.
func DeleteGroupJSON500Response(body InternalServerError) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// AddPermissionJSON201Response is a constructor method for a AddPermission response.
// A *Response is returned with the configured status code and content type from the spec.
func AddPermissionJSON201Response(body BasicResponse) *Response {
	return &Response{
		body:        body,
		Code:        201,
		contentType: "application/json",
	}
}

// AddPermissionJSON400Response is a constructor method for a AddPermission response.
// A *Response is returned with the configured status code and content type from the spec.
func AddPermissionJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// AddPermissionJSON401Response is a constructor method for a AddPermission response.
// A *Response is returned with the configured status code and content type from the spec.
func AddPermissionJSON401Response(body Unauthorized) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// AddPermissionJSON500Response is a constructor method for a AddPermission response.
// A *Response is returned with the configured status code and content type from the spec.
func AddPermissionJSON500Response(body InternalServerError) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// DeletePermissionJSON200Response is a constructor method for a DeletePermission response.
// A *Response is returned with the configured status code and content type from the spec.
func DeletePermissionJSON200Response(body BasicResponse) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// DeletePermissionJSON400Response is a constructor method for a DeletePermission response.
// A *Response is returned with the configured status code and content type from the spec.
func DeletePermissionJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// DeletePermissionJSON401Response is a constructor method for a DeletePermission response.
// A *Response is returned with the configured status code and content type from the spec.
func DeletePermissionJSON401Response(body Unauthorized) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// DeletePermissionJSON500Response is a constructor method for a DeletePermission response.
// A *Response is returned with the configured status code and content type from the spec.
func DeletePermissionJSON500Response(body InternalServerError) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// UpdatePermissionJSON200Response is a constructor method for a UpdatePermission response.
// A *Response is returned with the configured status code and content type from the spec.
func UpdatePermissionJSON200Response(body BasicResponse) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// UpdatePermissionJSON400Response is a constructor method for a UpdatePermission response.
// A *Response is returned with the configured status code and content type from the spec.
func UpdatePermissionJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// UpdatePermissionJSON401Response is a constructor method for a UpdatePermission response.
// A *Response is returned with the configured status code and content type from the spec.
func UpdatePermissionJSON401Response(body Unauthorized) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// UpdatePermissionJSON500Response is a constructor method for a UpdatePermission response.
// A *Response is returned with the configured status code and content type from the spec.
func UpdatePermissionJSON500Response(body InternalServerError) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// FindApplicationByIDJSON200Response is a constructor method for a FindApplicationByID response.
// A *Response is returned with the configured status code and content type from the spec.
func FindApplicationByIDJSON200Response(body Application) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// FindApplicationByIDJSON400Response is a constructor method for a FindApplicationByID response.
// A *Response is returned with the configured status code and content type from the spec.
func FindApplicationByIDJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// FindApplicationByIDJSON401Response is a constructor method for a FindApplicationByID response.
// A *Response is returned with the configured status code and content type from the spec.
func FindApplicationByIDJSON401Response(body Unauthorized) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// FindApplicationByIDJSON500Response is a constructor method for a FindApplicationByID response.
// A *Response is returned with the configured status code and content type from the spec.
func FindApplicationByIDJSON500Response(body InternalServerError) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// GroupsListJSON200Response is a constructor method for a GroupsList response.
// A *Response is returned with the configured status code and content type from the spec.
func GroupsListJSON200Response(body []Group) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GroupsListJSON400Response is a constructor method for a GroupsList response.
// A *Response is returned with the configured status code and content type from the spec.
func GroupsListJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// GroupsListJSON401Response is a constructor method for a GroupsList response.
// A *Response is returned with the configured status code and content type from the spec.
func GroupsListJSON401Response(body Unauthorized) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// GroupsListJSON500Response is a constructor method for a GroupsList response.
// A *Response is returned with the configured status code and content type from the spec.
func GroupsListJSON500Response(body InternalServerError) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// NewGroupJSON201Response is a constructor method for a NewGroup response.
// A *Response is returned with the configured status code and content type from the spec.
func NewGroupJSON201Response(body BasicCreationResponse) *Response {
	return &Response{
		body:        body,
		Code:        201,
		contentType: "application/json",
	}
}

// NewGroupJSON400Response is a constructor method for a NewGroup response.
// A *Response is returned with the configured status code and content type from the spec.
func NewGroupJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// NewGroupJSON401Response is a constructor method for a NewGroup response.
// A *Response is returned with the configured status code and content type from the spec.
func NewGroupJSON401Response(body Unauthorized) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// NewGroupJSON500Response is a constructor method for a NewGroup response.
// A *Response is returned with the configured status code and content type from the spec.
func NewGroupJSON500Response(body InternalServerError) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// UsersListJSON200Response is a constructor method for a UsersList response.
// A *Response is returned with the configured status code and content type from the spec.
func UsersListJSON200Response(body []User) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// UsersListJSON400Response is a constructor method for a UsersList response.
// A *Response is returned with the configured status code and content type from the spec.
func UsersListJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// UsersListJSON401Response is a constructor method for a UsersList response.
// A *Response is returned with the configured status code and content type from the spec.
func UsersListJSON401Response(body Unauthorized) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// UsersListJSON500Response is a constructor method for a UsersList response.
// A *Response is returned with the configured status code and content type from the spec.
func UsersListJSON500Response(body InternalServerError) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// NewUserJSON201Response is a constructor method for a NewUser response.
// A *Response is returned with the configured status code and content type from the spec.
func NewUserJSON201Response(body BasicResponse) *Response {
	return &Response{
		body:        body,
		Code:        201,
		contentType: "application/json",
	}
}

// NewUserJSON400Response is a constructor method for a NewUser response.
// A *Response is returned with the configured status code and content type from the spec.
func NewUserJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// NewUserJSON401Response is a constructor method for a NewUser response.
// A *Response is returned with the configured status code and content type from the spec.
func NewUserJSON401Response(body Unauthorized) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// NewUserJSON500Response is a constructor method for a NewUser response.
// A *Response is returned with the configured status code and content type from the spec.
func NewUserJSON500Response(body InternalServerError) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// UserUpdateJSON200Response is a constructor method for a UserUpdate response.
// A *Response is returned with the configured status code and content type from the spec.
func UserUpdateJSON200Response(body BasicResponse) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// UserUpdateJSON400Response is a constructor method for a UserUpdate response.
// A *Response is returned with the configured status code and content type from the spec.
func UserUpdateJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// UserUpdateJSON401Response is a constructor method for a UserUpdate response.
// A *Response is returned with the configured status code and content type from the spec.
func UserUpdateJSON401Response(body Unauthorized) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// UserUpdateJSON500Response is a constructor method for a UserUpdate response.
// A *Response is returned with the configured status code and content type from the spec.
func UserUpdateJSON500Response(body InternalServerError) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// LoginJSON200Response is a constructor method for a Login response.
// A *Response is returned with the configured status code and content type from the spec.
func LoginJSON200Response(body LoginResponse) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// LoginJSON400Response is a constructor method for a Login response.
// A *Response is returned with the configured status code and content type from the spec.
func LoginJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// LoginJSON401Response is a constructor method for a Login response.
// A *Response is returned with the configured status code and content type from the spec.
func LoginJSON401Response(body Unauthorized) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// LoginJSON500Response is a constructor method for a Login response.
// A *Response is returned with the configured status code and content type from the spec.
func LoginJSON500Response(body InternalServerError) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Lista todas as aplicações
	// (GET /applications)
	ApplicationsList(w http.ResponseWriter, r *http.Request) *Response
	// Cadastra uma aplicação
	// (POST /applications)
	NewApplication(w http.ResponseWriter, r *http.Request) *Response
	// Deleta um grupo de permissões de uma aplicação
	// (DELETE /applications/{application_id}/groups/{group_id})
	DeleteGroup(w http.ResponseWriter, r *http.Request, applicationID string, groupID string) *Response
	// Adiciona uma permissão de um grupo de usuários de uma aplicação
	// (POST /applications/{application_id}/groups/{group_id}/permissions)
	AddPermission(w http.ResponseWriter, r *http.Request, applicationID string, groupID string) *Response
	// Exclui uma permissão de um grupo de usuários de uma aplicação
	// (DELETE /applications/{application_id}/groups/{group_id}/permissions/{permission_key})
	DeletePermission(w http.ResponseWriter, r *http.Request, applicationID string, groupID string, permissionKey string) *Response
	// Atualiza uma permissão de um grupo de usuários de uma aplicação
	// (PUT /applications/{application_id}/groups/{group_id}/permissions/{permission_key})
	UpdatePermission(w http.ResponseWriter, r *http.Request, applicationID string, groupID string, permissionKey string) *Response
	// Todas as informações de uma aplicação
	// (GET /applications/{id})
	FindApplicationByID(w http.ResponseWriter, r *http.Request, id string) *Response
	// Lista os grupos de permissões de uma aplicação
	// (GET /applications/{id}/groups)
	GroupsList(w http.ResponseWriter, r *http.Request, id string) *Response
	// Cadastra um novo grupo de permissões de uma aplicação
	// (POST /applications/{id}/groups)
	NewGroup(w http.ResponseWriter, r *http.Request, id string) *Response
	// Lista os usuários de uma aplicação
	// (GET /applications/{id}/users)
	UsersList(w http.ResponseWriter, r *http.Request, id string) *Response
	// Cadastra um novo usuário
	// (POST /applications/{id}/users)
	NewUser(w http.ResponseWriter, r *http.Request, id string) *Response
	// Atualiza um usuário
	// (PUT /applications/{id}/users/{byEmail})
	UserUpdate(w http.ResponseWriter, r *http.Request, id string, byEmail openapi_types.Email) *Response
	// Autentica usuário
	// (POST /login)
	Login(w http.ResponseWriter, r *http.Request) *Response
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler          ServerInterface
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// ApplicationsList operation middleware
func (siw *ServerInterfaceWrapper) ApplicationsList(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.ApplicationsList(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// NewApplication operation middleware
func (siw *ServerInterfaceWrapper) NewApplication(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.NewApplication(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// DeleteGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroup(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "application_id" -------------
	var applicationID string

	if err := runtime.BindStyledParameter("simple", false, "application_id", chi.URLParam(r, "application_id"), &applicationID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "application_id"})
		return
	}

	// ------------- Path parameter "group_id" -------------
	var groupID string

	if err := runtime.BindStyledParameter("simple", false, "group_id", chi.URLParam(r, "group_id"), &groupID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "group_id"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.DeleteGroup(w, r, applicationID, groupID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// AddPermission operation middleware
func (siw *ServerInterfaceWrapper) AddPermission(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "application_id" -------------
	var applicationID string

	if err := runtime.BindStyledParameter("simple", false, "application_id", chi.URLParam(r, "application_id"), &applicationID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "application_id"})
		return
	}

	// ------------- Path parameter "group_id" -------------
	var groupID string

	if err := runtime.BindStyledParameter("simple", false, "group_id", chi.URLParam(r, "group_id"), &groupID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "group_id"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.AddPermission(w, r, applicationID, groupID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// DeletePermission operation middleware
func (siw *ServerInterfaceWrapper) DeletePermission(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "application_id" -------------
	var applicationID string

	if err := runtime.BindStyledParameter("simple", false, "application_id", chi.URLParam(r, "application_id"), &applicationID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "application_id"})
		return
	}

	// ------------- Path parameter "group_id" -------------
	var groupID string

	if err := runtime.BindStyledParameter("simple", false, "group_id", chi.URLParam(r, "group_id"), &groupID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "group_id"})
		return
	}

	// ------------- Path parameter "permission_key" -------------
	var permissionKey string

	if err := runtime.BindStyledParameter("simple", false, "permission_key", chi.URLParam(r, "permission_key"), &permissionKey); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "permission_key"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.DeletePermission(w, r, applicationID, groupID, permissionKey)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// UpdatePermission operation middleware
func (siw *ServerInterfaceWrapper) UpdatePermission(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "application_id" -------------
	var applicationID string

	if err := runtime.BindStyledParameter("simple", false, "application_id", chi.URLParam(r, "application_id"), &applicationID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "application_id"})
		return
	}

	// ------------- Path parameter "group_id" -------------
	var groupID string

	if err := runtime.BindStyledParameter("simple", false, "group_id", chi.URLParam(r, "group_id"), &groupID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "group_id"})
		return
	}

	// ------------- Path parameter "permission_key" -------------
	var permissionKey string

	if err := runtime.BindStyledParameter("simple", false, "permission_key", chi.URLParam(r, "permission_key"), &permissionKey); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "permission_key"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.UpdatePermission(w, r, applicationID, groupID, permissionKey)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// FindApplicationByID operation middleware
func (siw *ServerInterfaceWrapper) FindApplicationByID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id string

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.FindApplicationByID(w, r, id)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GroupsList operation middleware
func (siw *ServerInterfaceWrapper) GroupsList(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id string

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GroupsList(w, r, id)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// NewGroup operation middleware
func (siw *ServerInterfaceWrapper) NewGroup(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id string

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.NewGroup(w, r, id)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// UsersList operation middleware
func (siw *ServerInterfaceWrapper) UsersList(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id string

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.UsersList(w, r, id)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// NewUser operation middleware
func (siw *ServerInterfaceWrapper) NewUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id string

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.NewUser(w, r, id)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// UserUpdate operation middleware
func (siw *ServerInterfaceWrapper) UserUpdate(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id string

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	// ------------- Path parameter "byEmail" -------------
	var byEmail openapi_types.Email

	if err := runtime.BindStyledParameter("simple", false, "byEmail", chi.URLParam(r, "byEmail"), &byEmail); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "byEmail"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.UserUpdate(w, r, id, byEmail)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.Login(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter %s: %v", err.paramName, err.err)
}

func (err UnescapedCookieParamError) Unwrap() error { return err.err }

type UnmarshalingParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err UnmarshalingParamError) Error() string {
	return fmt.Sprintf("error unmarshaling parameter %s as JSON: %v", err.paramName, err.err)
}

func (err UnmarshalingParamError) Unwrap() error { return err.err }

type RequiredParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err RequiredParamError) Error() string {
	if err.err == nil {
		return fmt.Sprintf("query parameter %s is required, but not found", err.paramName)
	} else {
		return fmt.Sprintf("query parameter %s is required, but errored: %s", err.paramName, err.err)
	}
}

func (err RequiredParamError) Unwrap() error { return err.err }

type RequiredHeaderError struct {
	paramName string
}

// Error implements error.
func (err RequiredHeaderError) Error() string {
	return fmt.Sprintf("header parameter %s is required, but not found", err.paramName)
}

type InvalidParamFormatError struct {
	err       error
	paramName string
}

// Error implements error.
func (err InvalidParamFormatError) Error() string {
	return fmt.Sprintf("invalid format for parameter %s: %v", err.paramName, err.err)
}

func (err InvalidParamFormatError) Unwrap() error { return err.err }

type TooManyValuesForParamError struct {
	NumValues int
	paramName string
}

// Error implements error.
func (err TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("expected one value for %s, got %d", err.paramName, err.NumValues)
}

// ParameterName is an interface that is implemented by error types that are
// relevant to a specific parameter.
type ParameterError interface {
	error
	// ParamName is the name of the parameter that the error is referring to.
	ParamName() string
}

func (err UnescapedCookieParamError) ParamName() string  { return err.paramName }
func (err UnmarshalingParamError) ParamName() string     { return err.paramName }
func (err RequiredParamError) ParamName() string         { return err.paramName }
func (err RequiredHeaderError) ParamName() string        { return err.paramName }
func (err InvalidParamFormatError) ParamName() string    { return err.paramName }
func (err TooManyValuesForParamError) ParamName() string { return err.paramName }

type ServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

type ServerOption func(*ServerOptions)

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface, opts ...ServerOption) http.Handler {
	options := &ServerOptions{
		BaseURL:    "/",
		BaseRouter: chi.NewRouter(),
		ErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
	}

	for _, f := range opts {
		f(options)
	}

	r := options.BaseRouter
	wrapper := ServerInterfaceWrapper{
		Handler:          si,
		ErrorHandlerFunc: options.ErrorHandlerFunc,
	}

	r.Route(options.BaseURL, func(r chi.Router) {
		r.Get("/applications", wrapper.ApplicationsList)
		r.Post("/applications", wrapper.NewApplication)
		r.Delete("/applications/{application_id}/groups/{group_id}", wrapper.DeleteGroup)
		r.Post("/applications/{application_id}/groups/{group_id}/permissions", wrapper.AddPermission)
		r.Delete("/applications/{application_id}/groups/{group_id}/permissions/{permission_key}", wrapper.DeletePermission)
		r.Put("/applications/{application_id}/groups/{group_id}/permissions/{permission_key}", wrapper.UpdatePermission)
		r.Get("/applications/{id}", wrapper.FindApplicationByID)
		r.Get("/applications/{id}/groups", wrapper.GroupsList)
		r.Post("/applications/{id}/groups", wrapper.NewGroup)
		r.Get("/applications/{id}/users", wrapper.UsersList)
		r.Post("/applications/{id}/users", wrapper.NewUser)
		r.Put("/applications/{id}/users/{byEmail}", wrapper.UserUpdate)
		r.Post("/login", wrapper.Login)
	})
	return r
}

func WithRouter(r chi.Router) ServerOption {
	return func(s *ServerOptions) {
		s.BaseRouter = r
	}
}

func WithServerBaseURL(url string) ServerOption {
	return func(s *ServerOptions) {
		s.BaseURL = url
	}
}

func WithErrorHandler(handler func(w http.ResponseWriter, r *http.Request, err error)) ServerOption {
	return func(s *ServerOptions) {
		s.ErrorHandlerFunc = handler
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaTW/bOBP+KwTf96jU7scCCwM9JG1aZFEUwbbBHtqgYMSxzUYitSTlxDX0YxY9FHvY",
	"Yy979R9bkNR3JH/ESmynBYrGlmlyhvM8M5zHnGFfhJHgwLXCgxmWoCLBFdg3z/p988cXXAPX5iWJooD5",
	"RDPBe5+V4OaZ8scQEvPq/xKGeID/1yvm7LlPVe9YSiFxkiQepqB8ySIzCR7gI0KRhD9jUBonHn7Wf9zZ",
	"mmecxHosJPsCtGnp6uce/qVDf0+4BslJ8A7kBGSr99kw5MahbKCXLmPjcFhYYY2ilJnXJDiVIgKpmQnX",
	"kAQKPByVHs0wo+b/oZAh0XiA45hR7GE9jQAPsNKS8ZFxnJMQzMDaB4mHTWSYBIoHH7D9rh16ns8hLj6D",
	"bwN3RBTzX0iwZv6ewmhNc4cA9IL4lw22eKv50mRyPmur2d2bW7NjoQku5ltZ+rUUcXSvmPJwBDJkSjHB",
	"7XRVPhwrDcjYpwWa/40ssZQWKIKAIApDxtn82/yrQBRQOtH8OygkOAVEkD8mEzBfFIhR4JoNmU+okIgK",
	"JMGPpRIIkEATEgjpxvH5vyFIgSjJJ/wq8I29auVC1aGmTW5KBVuJ9hsxYvyFBLszJFBrWkGqaWgxAjx8",
	"fTASB3CtJTnQZGRnmJCAUaLNsNxo4wGEhAWVOd2TjSaNiFJXQlbRmj+87dReyPjzX72QXD9/+sRl9PL+",
	"l/fIy73IV22Nyl0kTC0ugS+HjBu2JE2+havbV6HmVLBGMGsWt9agt3B1m4y2mX0WEU9brPTKiDihbVaf",
	"KVg3J3TNGc993XgxMnt4QjsmeUe7vCVip9G8wehit5pCe5qXhjWjewnTbvaqYkA6HeMaRiA3YKAxrzJ5",
	"k/PvNNGxwyqPQ5sdfc0mZhsZT1+eN5wcKsfyrRTKO6RjRq/dPci3HtxUHs9FjU8a9SX8cXuQz9kWhLPI",
	"QHFdFOx4/uJwddxR8i5yNoer007zYi0ddhP+LDILAm9WMid1pqfvzJwupBdAJMjDWI+Ld68yH3/74z1O",
	"G2Yzk/u0cHisdeRSGOND0dRzRODbTmH+zTYTlKDD0xMUEUmQQCZLHACn5jGxtdx1IB+xMcccpX2ihfyI",
	"H5klmQ7MmpWPsIcnIF0Sxo8f9R/1Db5FBJxEDA/wU/vIFBU9tt72SocGh2iwcoQBeXaSGJRlAfWGKY29",
	"qnzzZE05g2kIl8a3fApM8i0mUpJpk75h7DKNW7Fz30GVdJ6mpXInemZQocssHmsGlcGDBx+qsPlwnpx7",
	"WMVhSOQ0N00LShQy/8oGetgxonKgV/jcVFShGmJROx878IPSR4JOO9OUaovUqrKWMSQ3INCdmtYs8DRp",
	"Wi/rVPEJJUpLQokLfX+V0Pd3AyYvUttRHFacasdI4lUJ3JuV3n1iNOnZNKh6M/vXPHFJKQANN6H10j5/",
	"nRZMk5RC0CCVtZxxm+P1OKvoA1xdDNch4pXCvfQ8sWJts19PEq/RnszJ+7TkfMNUuJQHi/D/WsaRQHDt",
	"B/H8Hyr2D/IWcQbwaGRdqWltFBZwwUH7dizo1aTB5lR7SGmprfrJiDUY0X1JKkViG+VoEQ1PczUXEcp8",
	"0zrsY/05TG23nCsUasfCgqCxiud/SSaW0LOiVW/K0d6sePPpEqYrlLGfzO3IkurOL7Tnlutvu4yW+JvV",
	"0j2k77Exnd0FeT0cxQ3l0UkmP3m2dzzbfnHeDrmJjknAvuxncU5tv5/inDaKjWLQK8ZpSRw4mp68XIn5",
	"D6cvuyGN1G/aWF8Kia8cg70D3vtMtmJVt2ATmaI48LXCzMoQmdr40NC1kgDqhJiVpU+bA1Sthd4/vDln",
	"hGr2Z0VJYIF4urq89SDa5tzjXdZwRVrAcvVW7LV6i7iYiG4VLZMwY2XB2pIvz8ynP3K6tD+lr/NDUX5W",
	"2uMkueJ5z0FnYV602/cjpUWHlx2TEl02zKL6sBJi5lUDLhckvN7sYmovMdiOpFmIyO9v7CCAm5v91KfV",
	"DOnout1dcal8fWbXuv+zjEl57y/2uvdfRqJAjBhv/0XL3gC+ozsDN+583zMWqrebG7DwXlwCtzdEYu1u",
	"zOxYS14EPDOwKdwK0ouQSZIk/wUAAP//41T2blY1AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
