// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: permissions.sql

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

const addOrUpdateKeyInGroup = `-- name: AddOrUpdateKeyInGroup :exec
UPDATE groups
SET
    permissions = jsonb_set(permissions, $3, $4, true)
WHERE
    id = $2 AND application_id = $1
`

type AddOrUpdateKeyInGroupParams struct {
	ApplicationID uuid.UUID
	ID            uuid.UUID
	Path          interface{}
	Replacement   []byte
}

func (q *Queries) AddOrUpdateKeyInGroup(ctx context.Context, arg AddOrUpdateKeyInGroupParams) error {
	_, err := q.db.Exec(ctx, addOrUpdateKeyInGroup,
		arg.ApplicationID,
		arg.ID,
		arg.Path,
		arg.Replacement,
	)
	return err
}

const removeKeyInGroup = `-- name: RemoveKeyInGroup :exec
UPDATE groups
SET
    permissions = permissions - $3
WHERE
    id = $2 AND application_id = $1
`

type RemoveKeyInGroupParams struct {
	ApplicationID uuid.UUID
	ID            uuid.UUID
	Permissions   []byte
}

func (q *Queries) RemoveKeyInGroup(ctx context.Context, arg RemoveKeyInGroupParams) error {
	_, err := q.db.Exec(ctx, removeKeyInGroup, arg.ApplicationID, arg.ID, arg.Permissions)
	return err
}
