// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: permissions.sql

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

const addOrUpdatePermissionInGroup = `-- name: AddOrUpdatePermissionInGroup :exec
UPDATE groups
SET
    permissions = jsonb_set(permissions, $3, $4, true)
WHERE
    id = $2 AND application_id = $1
`

type AddOrUpdatePermissionInGroupParams struct {
	ApplicationID uuid.UUID
	ID            uuid.UUID
	Path          interface{}
	Replacement   []byte
}

func (q *Queries) AddOrUpdatePermissionInGroup(ctx context.Context, arg AddOrUpdatePermissionInGroupParams) error {
	_, err := q.db.Exec(ctx, addOrUpdatePermissionInGroup,
		arg.ApplicationID,
		arg.ID,
		arg.Path,
		arg.Replacement,
	)
	return err
}

const removePermissionFromGroup = `-- name: RemovePermissionFromGroup :exec
UPDATE groups
SET
    permissions = permissions - $3
WHERE
    id = $2 AND application_id = $1
`

type RemovePermissionFromGroupParams struct {
	ApplicationID uuid.UUID
	ID            uuid.UUID
	Permissions   []byte
}

func (q *Queries) RemovePermissionFromGroup(ctx context.Context, arg RemovePermissionFromGroupParams) error {
	_, err := q.db.Exec(ctx, removePermissionFromGroup, arg.ApplicationID, arg.ID, arg.Permissions)
	return err
}
